In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("C:\\Users\\jojic\\OneDrive\\Desktop\\mljourney\\ml-model-works\\regression_works\\car-price-prediction\\Car.csv.xls")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8148 entries, 0 to 8147
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           8148 non-null   object
 1   year           8148 non-null   int64
 2   selling_price  8148 non-null   int64
 3   km_driven      8148 non-null   int64
 4   fuel           8148 non-null   object
 5   seller_type    8148 non-null   object
 6   transmission   8148 non-null   object
 7   owner          8148 non-null   object
 8   mileage        7927 non-null   object
 9   engine         7927 non-null   object
 10  max_power      7933 non-null   object
 11  torque         7926 non-null   object
 12  seats          7927 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 827.7+ KB

In [ ]:
df.head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Alto 800 LXI Opt,2023,410000,10000,Petrol,Individual,Manual,First Owner,19.03 kmpl,999 CC,71.01bhp,96Nm,5.0
1,Skoda Slavia 1.0 TSI Ambition,2023,1350000,10000,Petrol,Individual,Manual,First Owner,14.08 kmpl,1956 CC,167.67bhp,350nm,5.0
2,BMW 3 Series Gran Limousine 320Ld Luxury Line,2023,5800000,1000,Diesel,Dealer,Automatic,First Owner,18.15 kmpl,998 CC,118.35bhp,172Nm,5.0
3,MG ZS EV Exclusive,2023,2650000,10000,Electric,Dealer,Automatic,First Owner,32.52 kmpl,998 CC,58.33bhp,78Nm,5.0
4,Tata Punch Adventure,2023,715000,10000,Petrol,Individual,Manual,First Owner,12.15 kmpl,1451 CC,141bhp,250Nm,5.0

In [ ]:
df.isnull().sum()

Name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="most_frequent")
df.iloc[:,10:-1] = imputer.fit_transform(df.iloc[:,10:-1])

In [ ]:
df.isnull().sum()

In [ ]:
df["mileage"] = df["mileage"].str.replace("kmpl","")
df["mileage"] = df["mileage"].str.replace("km/kg","")

df["engine"] = df["engine"].str.replace("CC","")

df["max_power"] = df["max_power"].str.replace("bhp","")

df["torque"] = df["torque"].str.replace("nm","Nm")
df["torque"] = df["torque"].str.replace("Nm","")

In [ ]:
df.head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Alto 800 LXI Opt,2023,410000,10000,Petrol,Individual,Manual,First Owner,19.03,999,71.01,96,5.0
1,Skoda Slavia 1.0 TSI Ambition,2023,1350000,10000,Petrol,Individual,Manual,First Owner,14.08,1956,167.67,350,5.0
2,BMW 3 Series Gran Limousine 320Ld Luxury Line,2023,5800000,1000,Diesel,Dealer,Automatic,First Owner,18.15,998,118.35,172,5.0
3,MG ZS EV Exclusive,2023,2650000,10000,Electric,Dealer,Automatic,First Owner,32.52,998,58.33,78,5.0
4,Tata Punch Adventure,2023,715000,10000,Petrol,Individual,Manual,First Owner,12.15,1451,141,250,5.0

In [ ]:
"""df["mileage"] = df["mileage"].astype("float")
df["engine"] = df["engine"].astype("float")
df["max_power"] = df["max_power"].astype("float")
df["torque"] = df["torque"].astype("float") """

ValueError: could not convert string to float: ' '