In [450]:
import pandas as pd
import numpy as np

In [451]:
df=pd.read_csv("C:\\Users\\jojic\\OneDrive\\Desktop\\mljourney\\ml-model-works\\regression_works\\car-price-prediction\\Car.csv.xls")

In [452]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8148 entries, 0 to 8147
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           8148 non-null   object
 1   year           8148 non-null   int64
 2   selling_price  8148 non-null   int64
 3   km_driven      8148 non-null   int64
 4   fuel           8148 non-null   object
 5   seller_type    8148 non-null   object
 6   transmission   8148 non-null   object
 7   owner          8148 non-null   object
 8   mileage        7927 non-null   object
 9   engine         7927 non-null   object
 10  max_power      7933 non-null   object
 11  torque         7926 non-null   object
 12  seats          7927 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 827.7+ KB

In [453]:
df.head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Alto 800 LXI Opt,2023,410000,10000,Petrol,Individual,Manual,First Owner,19.03 kmpl,999 CC,71.01bhp,96Nm,5.0
1,Skoda Slavia 1.0 TSI Ambition,2023,1350000,10000,Petrol,Individual,Manual,First Owner,14.08 kmpl,1956 CC,167.67bhp,350nm,5.0
2,BMW 3 Series Gran Limousine 320Ld Luxury Line,2023,5800000,1000,Diesel,Dealer,Automatic,First Owner,18.15 kmpl,998 CC,118.35bhp,172Nm,5.0
3,MG ZS EV Exclusive,2023,2650000,10000,Electric,Dealer,Automatic,First Owner,32.52 kmpl,998 CC,58.33bhp,78Nm,5.0
4,Tata Punch Adventure,2023,715000,10000,Petrol,Individual,Manual,First Owner,12.15 kmpl,1451 CC,141bhp,250Nm,5.0

In [454]:
df.isnull().sum()

Name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [455]:
df.columns

Index(['Name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [456]:
df["mileage"] = df["mileage"].str.replace("kmpl","")
df["mileage"] = df["mileage"].str.replace("km/kg","")
df["mileage"] = df["mileage"].astype("float")

df["engine"] = df["engine"].str.replace("CC","")
df["engine"] = df["engine"].astype("float")

df["max_power"] = df["max_power"].str.replace("bhp","")
df.drop(df[df["max_power"]==' '].index,inplace=True)
df["max_power"] = df["max_power"].astype("float")

df["torque"] = df["torque"].str.replace("nm","Nm")
df["torque"] = df["torque"].str.replace("@","Nm")
df["torque"] = df["torque"].str.replace("kgm","Nm")
df["torque"] = df["torque"].str.replace("KGM","Nm")
df["torque"] = df["torque"].str.replace("/","Nm")
df["torque"] = df["torque"].str.replace("(","Nm")
df["torque"] = df["torque"].str.replace("Nm","NM")
df["torque"]=df["torque"].str.split("NM").str[0] 
df["torque"]=df["torque"].astype("float")

In [457]:
df.head()

,Name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Alto 800 LXI Opt,2023,410000,10000,Petrol,Individual,Manual,First Owner,19.03,999.0,71.01,96.0,5.0
1,Skoda Slavia 1.0 TSI Ambition,2023,1350000,10000,Petrol,Individual,Manual,First Owner,14.08,1956.0,167.67,350.0,5.0
2,BMW 3 Series Gran Limousine 320Ld Luxury Line,2023,5800000,1000,Diesel,Dealer,Automatic,First Owner,18.15,998.0,118.35,172.0,5.0
3,MG ZS EV Exclusive,2023,2650000,10000,Electric,Dealer,Automatic,First Owner,32.52,998.0,58.33,78.0,5.0
4,Tata Punch Adventure,2023,715000,10000,Petrol,Individual,Manual,First Owner,12.15,1451.0,141.00,250.0,5.0

In [458]:
df.isnull().sum()

Name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           221
seats            221
dtype: int64

In [459]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
df[["mileage","engine","max_power","torque","seats"]]=imputer.fit_transform(df[["mileage","engine","max_power","torque","seats"]])

In [460]:
df.isnull().sum()

Name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
mileage          0
engine           0
max_power        0
torque           0
seats            0
dtype: int64

In [461]:
df[df.duplicated].shape

(1202, 13)

In [462]:
df=df.drop_duplicates()

In [463]:
df[df.duplicated].shape

(0, 13)

In [464]:
df.dtypes

Name              object
year               int64
selling_price      int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage          float64
engine           float64
max_power        float64
torque           float64
seats            float64
dtype: object

In [465]:
df.columns

Index(['Name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner', 'mileage', 'engine', 'max_power', 'torque',
       'seats'],
      dtype='object')

In [466]:
x=df[['year','km_driven','fuel','seller_type','transmission','owner','mileage','engine','max_power','torque','seats']]
y=df[['selling_price']]

In [467]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("encoder",OneHotEncoder(),['fuel','seller_type','transmission','owner'])],remainder="passthrough")
x=pd.DataFrame(ct.fit_transform(x))
x

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2023.0,10000.0,19.03000,999.000000,71.0100,96.000000,5.000000
1,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2023.0,10000.0,14.08000,1956.000000,167.6700,350.000000,5.000000
2,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2023.0,1000.0,18.15000,998.000000,118.3500,172.000000,5.000000
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2023.0,10000.0,32.52000,998.000000,58.3300,78.000000,5.000000
4,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2023.0,10000.0,12.15000,1451.000000,141.0000,250.000000,5.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6940,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1994.0,100000.0,12.80000,1995.000000,52.0000,106.000000,5.000000
6941,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1994.0,100000.0,19.41866,1458.539364,91.6052,168.419818,5.415342
6942,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1994.0,60000.0,16.10000,796.000000,37.0000,59.000000,4.000000
6943,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1991.0,120000.0,19.41866,1458.539364,91.6052,168.419818,5.415342
6944,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1983.0,10000.0,19.41866,1458.539364,91.6052,168.419818,5.415342

In [468]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=42)

In [469]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)

In [470]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor
from sklearn.metrics import r2_score
models=[LinearRegression,DecisionTreeRegressor,KNeighborsRegressor,RandomForestRegressor,AdaBoostRegressor,GradientBoostingRegressor]
for model in models:
    md=model()
    md.fit(xtrain,ytrain)
    ypred=md.predict(xtest)
    print("===",model,"===")
    print("r2_score :",r2_score(ytest,ypred)*100)

=== <class 'sklearn.linear_model._base.LinearRegression'> ===
r2_score : 63.52614158331213
=== <class 'sklearn.tree._classes.DecisionTreeRegressor'> ===
r2_score : 78.93914902865917
=== <class 'sklearn.neighbors._regression.KNeighborsRegressor'> ===
r2_score : 86.20121126342912

C:\Users\jojic\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

=== <class 'sklearn.ensemble._forest.RandomForestRegressor'> ===
r2_score : 89.1338756391648

C:\Users\jojic\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

=== <class 'sklearn.ensemble._weight_boosting.AdaBoostRegressor'> ===
r2_score : 17.539136209700533

C:\Users\jojic\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\ensemble\_gb.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

=== <class 'sklearn.ensemble._gb.GradientBoostingRegressor'> ===
r2_score : 90.53612088288912